Upgrading PhoneGap for iOS to 3.0.0

diff --git a/iOS/cordova/emulate b/iOS/cordova/emulate
--- a/iOS/cordova/emulate
+++ b/iOS/cordova/emulate
@@ -19,7 +19,7 @@
 #
 
 XCODE_VER=$(xcodebuild -version | head -n 1 | sed -e 's/Xcode //')
-XCODE_MIN_VERSION="4.5"
+XCODE_MIN_VERSION="4.6"
 
 if [[ "$XCODE_VER" < "$XCODE_MIN_VERSION" ]]; then
 	echo "Cordova can only run in Xcode version $XCODE_MIN_VERSION or greater."
@@ -33,13 +33,13 @@ PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
 XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
 PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
 
-APP_PATH=${1:-$PROJECT_PATH/build/$(xcodebuild -project $PROJECT_NAME.xcodeproj -arch i386 -target $PROJECT_NAME -configuration Debug -sdk $SDK -showBuildSettings | grep FULL_PRODUCT_NAME | awk -F ' = ' '{print $2}')}
+APP_PATH=${1:-$PROJECT_PATH/build/emulator/$(xcodebuild -project "$PROJECT_PATH/$PROJECT_NAME.xcodeproj" -arch i386 -target "$PROJECT_NAME" -configuration Debug -sdk $SDK -showBuildSettings | grep FULL_PRODUCT_NAME | awk -F ' = ' '{print $2}')}
 
 DEVICE_FAMILY=${2:-${DEVICE_FAMILY:-iphone}}
 
 if [ ! -d "$APP_PATH" ]; then
 	echo "Project '$APP_PATH' is not built. Building."
-    $CORDOVA_PATH/build || exit $?
+    "$CORDOVA_PATH/build" || exit $?
 fi
 
 if [ ! -d "$APP_PATH" ]; then
@@ -47,10 +47,10 @@ if [ ! -d "$APP_PATH" ]; then
 	exit 1
 fi
 
-IOS_SIM_MIN_VERSION="1.5"
+IOS_SIM_MIN_VERSION="1.7"
 IOS_SIM_LOCATION=$(which ios-sim)
 if [ $? != 0 ]; then
-    echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'brew install ios-sim' using homebrew: http://mxcl.github.com/homebrew/\033[m"; exit 1;
+    echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'npm install -g ios-sim' using node.js: http://nodejs.org/\033[m"; exit 1;
 	exit 1
 fi
 
@@ -63,4 +63,3 @@ fi
 
 # launch using ios-sim
 ios-sim launch "$APP_PATH" --family "$DEVICE_FAMILY" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" &
-
diff --git a/iOS/cordova/lib/install-emulator b/iOS/cordova/lib/install-emulator
--- a/iOS/cordova/lib/install-emulator
+++ b/iOS/cordova/lib/install-emulator
@@ -83,7 +83,7 @@ case "$TARGET_LC" in
 esac
 
 XCODE_VER=$(xcodebuild -version | head -n 1 | sed -e 's/Xcode //')
-XCODE_MIN_VERSION="4.5"
+XCODE_MIN_VERSION="4.6"
 
 if [[ "$XCODE_VER" < "$XCODE_MIN_VERSION" ]]; then
 	echo "Cordova can only run in Xcode version $XCODE_MIN_VERSION or greater."
@@ -96,22 +96,22 @@ PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
 XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
 PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
 
-APP_PATH="$PROJECT_PATH/build/$PROJECT_NAME.app"
+SIMULATOR_APP_PATH="$PROJECT_PATH/build/emulator/$PROJECT_NAME.app"
 
-if [ ! -d "$APP_PATH" ]; then
-	echo "Project '$APP_PATH' is not built."
+if [ ! -d "$SIMULATOR_APP_PATH" ]; then
+	echo "Project '$SIMULATOR_APP_PATH' is not built."
     exit 1
 fi
 
-if [ ! -d "$APP_PATH" ]; then
-	echo "$APP_PATH not found to emulate."
+if [ ! -d "$SIMULATOR_APP_PATH" ]; then
+	echo "$SIMULATOR_APP_PATH not found to emulate."
 	exit 1
 fi
 
-IOS_SIM_MIN_VERSION="1.5"
+IOS_SIM_MIN_VERSION="1.7"
 IOS_SIM_LOCATION=$(which ios-sim)
 if [ $? != 0 ]; then
-    echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'brew install ios-sim' using homebrew: http://mxcl.github.com/homebrew/\033[m"; exit 1;
+    echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'npm install -g ios-sim' using node.js: http://nodejs.org/\033[m"; exit 1;
 	exit 1
 fi
 
@@ -123,6 +123,6 @@ if [[ "$IOS_SIM_VERSION" < "$IOS_SIM_MIN_VERSION" ]]; then
 fi
 
 # launch using ios-sim
-ios-sim launch "$APP_PATH" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" $TARGET_FLAG --exit
+ios-sim launch "$SIMULATOR_APP_PATH" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" $TARGET_FLAG --exit
 
 
diff --git a/iOS/cordova/run b/iOS/cordova/run
--- a/iOS/cordova/run
+++ b/iOS/cordova/run
@@ -54,6 +54,10 @@ _parseArgs()
       "--target")
         TARGET=${OPTION_RESULT[1]}
         ;;
+    "--device")
+      echo "Targeting a device is not supported currently."
+      exit 1
+      ;;
     esac
   done
 }
@@ -89,7 +93,7 @@ case "$TARGET_LC" in
 esac
 
 XCODE_VER=$(xcodebuild -version | head -n 1 | sed -e 's/Xcode //')
-XCODE_MIN_VERSION="4.5"
+XCODE_MIN_VERSION="4.6"
 
 if [[ "$XCODE_VER" < "$XCODE_MIN_VERSION" ]]; then
 	echo "Cordova can only run in Xcode version $XCODE_MIN_VERSION or greater."
@@ -101,19 +105,40 @@ PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
 XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcodeproj  )
 PROJECT_NAME=$(basename "$XCODEPROJ" .xcodeproj)
 
-APP_PATH="$PROJECT_PATH/build/$PROJECT_NAME.app"
+SIMULATOR_APP_PATH="$PROJECT_PATH/build/emulator/$PROJECT_NAME.app"
+DEVICE_APP_PATH="$PROJECT_PATH/build/device/$PROJECT_NAME.app"
 
-$CORDOVA_PATH/build || exit $?
+"$CORDOVA_PATH/build" || exit $?
 
-if [ ! -d "$APP_PATH" ]; then
-	echo "$APP_PATH not found to emulate."
+# if device build found, run it first
+if [ -d "$DEVICE_APP_PATH" ]; then
+    IOS_DEPLOY_MIN_VERSION="1.0.2"
+    IOS_DEPLOY_LOCATION=$(which ios-deploy)
+    if [ $? != 0 ]; then
+        echo -e "\033[31mError: ios-deploy was not found. Please download, build and install version $IOS_DEPLOY_MIN_VERSION or greater from https://github.com/phonegap/ios-deploy into your path. Or 'npm install -g ios-deploy' using node.js: http://nodejs.org/\033[m"; exit 1;
+    	exit 1
+    fi
+
+    IOS_DEPLOY_VERSION=$(ios-deploy --version)
+    if [[ "$IOS_DEPLOY_VERSION" < "$IOS_DEPLOY_MIN_VERSION" ]]; then
+    	echo "Cordova needs ios-deploy version $IOS_DEPLOY_MIN_VERSION or greater, you have version $IOS_DEPLOY_VERSION."
+    	exit 1
+    fi
+    
+    # if we got here, we can deploy the app, then exit success
+    ios-deploy -d -b "$DEVICE_APP_PATH"
+	exit 0
+fi
+
+if [ ! -d "$SIMULATOR_APP_PATH" ]; then
+	echo "$SIMULATOR_APP_PATH not found to emulate."
 	exit 1
 fi
 
-IOS_SIM_MIN_VERSION="1.5"
+IOS_SIM_MIN_VERSION="1.7"
 IOS_SIM_LOCATION=$(which ios-sim)
 if [ $? != 0 ]; then
-    echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'brew install ios-sim' using homebrew: http://mxcl.github.com/homebrew/\033[m"; exit 1;
+    echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'npm install -g ios-sim' using node.js: http://nodejs.org/\033[m"; exit 1;
 	exit 1
 fi
 
@@ -125,4 +150,4 @@ if [[ "$IOS_SIM_VERSION" < "$IOS_SIM_MIN_VERSION" ]]; then
 fi
 
 # launch using ios-sim
-ios-sim launch "$APP_PATH" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" $TARGET_FLAG &
+ios-sim launch "$SIMULATOR_APP_PATH" --stderr "$CORDOVA_PATH/console.log" --stdout "$CORDOVA_PATH/console.log" $TARGET_FLAG &
